version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: arko_user
      POSTGRES_PASSWORD: arko_password
      POSTGRES_DB: arko360
    volumes:
      - arko_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://arko_user:arko_password@db:5432/arko360
      - SECRET_KEY=changethisinproduction
    depends_on:
      - db


volumes:
  arko_db_data:
